### ISSUE TITLE
As a developer, I need a dev environment

### ISSUE THREAD

**Issue by heyozramos** [heyozramos/PoseCursor#1]
## Scope
- [ ] I can type `npm start` to launch a local dev server
- [ ] I can type `npm run build` to build the project
- [ ] I can type `npm run deploy` to deploy the site to my configured server

## Tasks
- [ ] Setup `.gitignore`, `README.md`, and `package.json`
